QLBanHang/Models/ErrorViewModel.cs
namespace QLBanHang.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

QLBanHang/Models/HangHoa.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace QLBanHang.Models;

public partial class HangHoa
{
   
    public int MaHang { get; set; }

    public int MaLoai { get; set; }

    public string TenHang { get; set; } = null!;

    [Range(100, 5000, ErrorMessage = "Giá phải nằm trong khoảng từ 100 đến 5000")]
	[RegularExpression(@"^\d*\.?\d+$", ErrorMessage = "Vui lòng nhập một số.")]
	public decimal? Gia { get; set; }

    [Required]
    [RegularExpression(@"^.*\.(jpg|png|gif|tiff)$", ErrorMessage = "Tên file phải có đuôi .jpg, .png, .gif, hoặc .tiff")]
    public string? Anh { get; set; }

    [BindNever]
    
	public virtual LoaiHang? MaLoaiNavigation { get; set; } = null!;
}

QLBanHang/Models/LoaiHang.cs
using System;
using System.Collections.Generic;

namespace QLBanHang.Models;

public partial class LoaiHang
{
    public int MaLoai { get; set; }

    public string TenLoai { get; set; } = null!;

    public virtual ICollection<HangHoa> HangHoas { get; set; } = new List<HangHoa>();
}

QLBanHang/Models/QlhangHoaContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace QLBanHang.Models;

public partial class QlhangHoaContext : DbContext
{
    public QlhangHoaContext()
    {
    }

    public QlhangHoaContext(DbContextOptions<QlhangHoaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<HangHoa> HangHoas { get; set; }

    public virtual DbSet<LoaiHang> LoaiHangs { get; set; }

    public virtual DbSet<TblAccount> TblAccounts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Server= DUNGDEPTRAI\\SQLEXPRESS;Database=QLHangHoa;Trusted_Connection=True;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<HangHoa>(entity =>
        {
            entity.HasKey(e => e.MaHang);

            entity.ToTable("HangHoa");

            entity.Property(e => e.Anh).HasMaxLength(100);
            entity.Property(e => e.Gia).HasColumnType("numeric(18, 0)");
            entity.Property(e => e.TenHang).HasMaxLength(50);

            entity.HasOne(d => d.MaLoaiNavigation).WithMany(p => p.HangHoas)
                .HasForeignKey(d => d.MaLoai)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HangHoa_LoaiHang");
        });

        modelBuilder.Entity<LoaiHang>(entity =>
        {
            entity.HasKey(e => e.MaLoai);

            entity.ToTable("LoaiHang");

            entity.Property(e => e.TenLoai).HasMaxLength(50);
        });

        modelBuilder.Entity<TblAccount>(entity =>
        {
            entity.HasKey(e => e.Uid);

            entity.ToTable("tblAccount");

            entity.Property(e => e.Password)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.Username)
                .HasMaxLength(10)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

QLBanHang/Models/TblAccount.cs
using System;
using System.Collections.Generic;

namespace QLBanHang.Models;

public partial class TblAccount
{
    public int Uid { get; set; }

    public string? Username { get; set; }

    public string? Password { get; set; }
}

QLBanHang/Controllers/BaiThiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLBanHang.Models;

namespace QLBanHang.Controllers
{
    public class BaiThiController : Controller
    {
        private QlhangHoaContext _db;
        public BaiThiController(QlhangHoaContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
			List<HangHoa> dshanghoa = _db.HangHoas.ToList();
			return View(dshanghoa);
        }

        public IActionResult Create()
        {
            ViewBag.MaLoai = new SelectList(_db.LoaiHangs, "MaLoai", "TenLoai");
            return View();
        }
        [HttpPost]

        public IActionResult Create([Bind("MaLoai,TenHang,Gia,Anh")] HangHoa obj)
        {
            if(ModelState.IsValid)
            {
                _db.HangHoas.Add(obj);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            
            ViewBag.MaLoai = new SelectList(_db.LoaiHangs, "MaLoai", "TenLoai");
            return View();
        }

        public IActionResult HangHoaByID(int mid)
        {
            var hanghoas = _db.HangHoas.Where(h => h.MaLoai == mid).ToList();
            return PartialView("HangHoaTable", hanghoas);
        }

    }
}

QLBanHang/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using QLBanHang.Models;
using System.Diagnostics;

namespace QLBanHang.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

QLBanHang/Views/BaiThi/Create.cshtml
@{
    ViewData["Title"] = "Quản Lý Hàng Hoá";
    Layout = "~/Views/Shared/DoXuanKienLayout.cshtml";
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
@model HangHoa
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Category</h2>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="MaLoai" class=" p-0"></label>
            <select asp-for="MaLoai" asp-items="@ViewBag.MaLoai"></select>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="TenHang" class="p-0"></label>
            <input asp-for="TenHang" class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Gia" class="p-0"></label>
            <input asp-for="Gia" class="form-control" />
            <span asp-validation-for="Gia" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Anh" class="p-0"></label>
            <input asp-for="Anh" class="form-control" />
            <span asp-validation-for="Anh" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="BaiThi" asp-action="Index" class="btn btn-outline-secondary form-control">
                    Back to list
                </a>
            </div>
        </div>
    </div>
</form>

QLBanHang/Views/BaiThi/HangHoaTable.cshtml
@model IEnumerable<HangHoa>
<div class="content">
	<!-- Begin New Product -->
	<div class="content_top">
		<div class="heading">
			<h3>Nguyễn Trung Dũng</h3>
		</div>
		<div class="see">
			<p><a href="#">See all Products</a></p>
		</div>
		<div class="clear"></div>
	</div>
	<div class="section group">
		@foreach (var item in Model)
		{
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="images/@item.Anh" alt="" /></a>
				<h2>@item.TenHang </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">@item.Gia</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
		}
	</div>
	@section Scripts{
		<script>
			$("li").click(function (e) {
				var id = $(this).attr("MaLoai");
				$.ajax({
					url: "HangHoaByID",
					data: { mid: id },
					success: function (response) {
						$("div#section group").html(response);
					}
				});
			});
		</script>
	}
	<!-- End New Product -->
	<!-- Begin Feature Products -->
	<div class="content_bottom">
		<div class="heading">
			<h3>Feature Products</h3>
		</div>
		<div class="see">
			<p><a href="#">See all Products</a></p>
		</div>
		<div class="clear"></div>
	</div>
	<div class="section group">
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/new-pic1.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$849.99</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/new-pic2.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$599.99</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/new-pic4.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$799.99</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/new-pic3.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$899.99</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<!-- End Feature Products -->
</div>
		</div>

QLBanHang/Views/BaiThi/Index.cshtml
@{
    ViewData["Title"] = "Quản Lý Hàng Hoá";
    Layout = "~/Views/Shared/DoXuanKienLayout.cshtml";
}
@model IEnumerable<HangHoa>

	<!-- Begin New Product -->
	<div class="content_top">
		<div class="heading">
			<h3>Đỗ Xuân Kiên</h3>
		</div>
		<div class="see">
			<p><a href="#">See all Products</a></p>
		</div>
		<div class="clear"></div>
	</div>
	<div class="section group">
		@foreach (var item in Model) {
			<div class="grid_1_of_4 images_1_of_4">
				<a href="preview.html"><img src="images/@item.Anh" alt="" /></a>
				<h2>@item.TenHang </h2>
				<div class="price-details">
					<div class="price-number">
						<p><span class="rupees">@item.Gia</span></p>
					</div>
					<div class="add-cart">
						<h4><a href="preview.html">Add to Cart</a></h4>
					</div>
					<div class="clear"></div>
				</div>
			</div>
		}			
	</div>
	
	<!-- End New Product -->
	<!-- Begin Feature Products -->
	<div class="content_bottom">
		<div class="heading">
			<h3>Feature Products</h3>
		</div>
		<div class="see">
			<p><a href="#">See all Products</a></p>
		</div>
		<div class="clear"></div>
	</div>
	<div class="section group">
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/new-pic1.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$849.99</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/new-pic2.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$599.99</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/new-pic4.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$799.99</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/new-pic3.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$899.99</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<!-- End Feature Products -->

	

QLBanHang/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Quan Ly Hang Hoa";

}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

QLBanHang/Views/Shared/Components/Render/RenderDoXuanKien_Header_bottom.cshtml
@model IEnumerable<LoaiHang>

<div class="menu">
	<ul>
		<li class="active"><a href="index.html">Nguyễn Trung Dũng</a></li>
		@foreach (var item in Model)
		{
			<li id="@item.MaLoai"><a>@item.TenLoai</a></li>
		}
		<div class="clear"></div>
	</ul>
</div>

<div class="search_box">
	<form>
		<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
		<input type="button" value="">
	</form>
</div>
<div class="clear"></div>

QLBanHang/Views/Shared/DoXuanKienLayout.cshtml
<!DOCTYPE HTML>
<head>
	<title>Free Home Shoppe Website Template | Home :: w3layouts</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/css/slider.css" rel="stylesheet" type="text/css" media="all" />
	
	<script type="text/javascript" src="js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="js/startstop-slider.js"></script>
</head>
<body>
	<!-- Begin Wrap -->
	<div class="wrap">
		<!-- Begin Header -->
		<partial name="DoXuanKien_Header" />
		<!-- End Header -->
		<!-- Begin Main -->
		<div class="main">
			<div class="content">
			@RenderBody()
			</div>
		<!-- End Main -->
		</div>
	</div>
	<!-- End Wrap -->
	<!-- Begin Footer -->
	<partial name="DoXuanKien_Footer" />
	<!-- End Footer -->
    <script src="~/js/jquery-1.7.2.min.js"></script>
	@RenderSection("Scripts", required:false);
</body>

QLBanHang/Views/Shared/DoXuanKien_Footer.cshtml
<div class="footer">
	<div class="wrap">
		<div class="section group">
			<div class="col_1_of_4 span_1_of_4">
				<h4>Information</h4>
				<ul>
					<li><a href="about.html">About Us</a></li>
					<li><a href="contact.html">Customer Service</a></li>
					<li><a href="#">Advanced Search</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>Why buy from us</h4>
				<ul>
					<li><a href="about.html">About Us</a></li>
					<li><a href="contact.html">Customer Service</a></li>
					<li><a href="#">Privacy Policy</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>My account</h4>
				<ul>
					<li><a href="contact.html">Sign In</a></li>
					<li><a href="index.html">View Cart</a></li>
					<li><a href="#">My Wishlist</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>Contact</h4>
				<ul>
					<li><span>+91-123-456789</span></li>
					<li><span>+00-123-000000</span></li>
				</ul>
			</div>
		</div>
	</div>
</div>

QLBanHang/Views/Shared/DoXuanKien_Header.cshtml
<div class="header">
	<div class="header_top">
		<div class="logo">
			<a href="index.html"><img src="images/logo.png" alt="" /></a>
		</div>
		<div class="cart">
			<p>
				Welcome Nguyen Trung Dung Online Store! <span>Cart:</span><div id="dd" class="wrapper-dropdown-2">
					0 item(s) - $0.00
					<ul class="dropdown">
						<li>you have no items in your Shopping cart</li>
					</ul>
				</div>
			</p>
		</div>
		<div class="clear"></div>
	</div>
	<div class="header_bottom">
		@* <partial name="DoXuanKien_header_bottom" /> *@
		@await Component.InvokeAsync("Render")
	</div>
	
</div>

	<script>
		$("li").click(function (e) {
			var id = $(this).attr("id");
			$.ajax({
				url: "BaiThi/HangHoaByID",
				data: { mid: id },
				success: function (response) {
					$("div.content").html(response);
				}
			});
		});
	</script>

QLBanHang/Views/Shared/DoXuanKien_Main.cshtml
<div class="content">
	<!-- Begin New Product -->
	<div class="content_top">
		<div class="heading">
			<h3>New Products</h3>
		</div>
		<div class="see">
			<p><a href="#">See all Products</a></p>
		</div>
		<div class="clear"></div>
	</div>
	<div class="section group">
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/feature-pic1.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$620.87</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/feature-pic2.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$899.75</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/feature-pic3.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$599.00</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/feature-pic4.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$679.87</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/feature-pic4.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$679.87</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<!-- End New Product -->
	<!-- Begin Feature Products -->
	<div class="content_bottom">
		<div class="heading">
			<h3>Feature Products</h3>
		</div>
		<div class="see">
			<p><a href="#">See all Products</a></p>
		</div>
		<div class="clear"></div>
	</div>
	<div class="section group">
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/new-pic1.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$849.99</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/new-pic2.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$599.99</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/new-pic4.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$799.99</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="grid_1_of_4 images_1_of_4">
			<a href="preview.html"><img src="images/new-pic3.jpg" alt="" /></a>
			<h2>Lorem Ipsum is simply </h2>
			<div class="price-details">
				<div class="price-number">
					<p><span class="rupees">$899.99</span></p>
				</div>
				<div class="add-cart">
					<h4><a href="preview.html">Add to Cart</a></h4>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<!-- End Feature Products -->
</div>
		</div>

QLBanHang/Views/Shared/DoXuanKien_header_bottom.cshtml
<div class="menu">
	<ul>
		<li class="active"><a href="index.html">Home</a></li>
		<li><a href="about.html">About</a></li>
		<li><a href="delivery.html">Delivery</a></li>
		<li><a href="news.html">News</a></li>
		<li><a href="contact.html">Contact</a></li>
		<div class="clear"></div>
	</ul>
</div>
<div class="search_box">
	<form>
		<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
		<input type="button" value="">
	</form>
</div>
<div class="clear"></div>

QLBanHang/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QLBanHang</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QLBanHang.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QLBanHang</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - QLBanHang - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>